import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import ts from 'typescript';
const source=ts.transpileModule(fs.readFileSync(new URL('../lib/capture.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
let constraints,trackStopped=0,closed=0,node,ended,failContext=false;
const track={label:'DJI test receiver',getSettings:()=>({deviceId:'dji-usb'}),stop(){trackStopped++},addEventListener(name,fn){if(name==='ended')ended=fn}};
const sandbox={exports:{},Blob,Float32Array,ArrayBuffer,DataView,Math,navigator:{mediaDevices:{async getUserMedia(c){constraints=c;return {getAudioTracks:()=>[track],getTracks:()=>[track]}}}},AudioContext:class{constructor(){if(failContext)throw Error('context unavailable');this.sampleRate=16000;this.destination={}}createMediaStreamSource(){return {connect(){},disconnect(){}}}createScriptProcessor(){node={connect(){},disconnect(){}};return node}createGain(){return {gain:{value:1},connect(){},disconnect(){}}}async resume(){}async close(){closed++}}};
vm.createContext(sandbox);vm.runInContext(source,sandbox);
let chunks=0,levels=[];
const monitor=await sandbox.exports.capture(()=>chunks++,v=>levels.push(v),{deviceId:'dji-usb',monitorOnly:true});
assert.equal(constraints.audio.deviceId.exact,'dji-usb');assert.equal(monitor.deviceName,'DJI test receiver');
const pcm=new Float32Array(4096).fill(.1),frame={inputBuffer:{getChannelData:()=>pcm}};
for(let i=0;i<50;i++)node.onaudioprocess(frame);
assert.equal(chunks,0,'microphone test must not emit any recording');assert.ok(levels.some(v=>v>0),'test should expose input level');monitor.stop();monitor.stop();assert.equal(trackStopped,1);assert.equal(closed,1);assert.equal(levels.at(-1),0);
let interrupted=0;const recording=await sandbox.exports.capture(()=>chunks++,()=>{},{onEnded:()=>interrupted++});
for(let i=0;i<35;i++)node.onaudioprocess(frame);assert.equal(chunks,1,'normal recording should still emit 8-second chunks');ended();assert.equal(interrupted,1);assert.equal(trackStopped,2);recording.stop();assert.equal(trackStopped,2);
failContext=true;await assert.rejects(sandbox.exports.capture(()=>{},()=>{}));assert.equal(trackStopped,3,'setup failures must release microphone');
console.log('PASS: selected USB device, level meter, no test audio emitted, recording chunks, interruption cleanup, idempotent stop, setup failure cleanup');
const converted=await sandbox.exports.wav(new Float32Array(48000).fill(.1),48000,16000).arrayBuffer();
assert.equal(new DataView(converted).getUint32(24,true),16000);
assert.equal(converted.byteLength,44+16000*2);
failContext=false;
let pause=true,emitted=[];
const backpressure=await sandbox.exports.capture((audio,offset)=>emitted.push(offset),()=>{},{windowSeconds:1,isPaused:()=>pause});
for(let i=0;i<5;i++)node.onaudioprocess(frame);
assert.equal(emitted.length,0);
pause=false;for(let i=0;i<4;i++)node.onaudioprocess(frame);
assert.equal(emitted.length,1);assert.ok(emitted[0]>=1,'waiting time must remain on the caption timeline');
backpressure.stop();
console.log('PASS: 48kHz to PCM16/16kHz conversion and bounded pause timeline');

let partialPause=false,partial=[];
const partialCapture=await sandbox.exports.capture((audio,offset)=>partial.push({audio,offset}),()=>{},{windowSeconds:1,isPaused:()=>partialPause});
node.onaudioprocess(frame);
partialPause=true;node.onaudioprocess(frame);
partialPause=false;for(let i=0;i<4;i++)node.onaudioprocess(frame);
assert.equal(partial.length,1);
assert.equal(partial[0].offset,8192/16000,'resume starts after dropped partial and paused audio');
assert.equal((await partial[0].audio.arrayBuffer()).byteLength,44+16384*2,'no pre-pause audio is joined');
partialCapture.stop();
console.log('PASS: partial audio is dropped across pause without shifting resumed captions');
