'use client';

import {useState,useEffect,useRef,useCallback} from 'react';
import {Mic,Users,BookOpen,Settings2,Plus,Download,Check,Edit3,Square,Languages,FileText,RefreshCw,CheckCircle2,Info,Copy,Maximize2,Minimize2,Volume2,MessageCircle,ArrowLeftRight,Search,Keyboard,Headphones,X,NotebookPen,Send,Reply} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import type {State,Person,Segment,Memory,Direction} from '@/lib/domain';
import {roles} from '@/lib/domain';
import {capture,type Capture} from '@/lib/capture';

function Picker({value,onChange,items,label,disabled=false}:{value:string;onChange:(s:string)=>void;items:{value:string;label:string}[];label:string;disabled?:boolean}){
 return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>;
}
function Turtle({className='',alt='禪學社龜龜'}:{className?:string;alt?:string}){return <img src="/art/turtle-logo.png" alt={alt} width={1147} height={1371} className={'turtle '+className}/>;}
function TurtleMood({pose='wave',className='',alt='禪學社龜龜'}:{pose?:'wave'|'listen'|'speak'|'notes';className?:string;alt?:string}){return <span className={'turtle-mood mood-'+pose+' '+className} role={alt?'img':undefined} aria-label={alt||undefined} aria-hidden={alt?undefined:true}/>;}
const EMPTY:State={people:[],sessions:[],segments:[],memories:[],sessionId:null,connection:{openai:false,asr:'gpt-transcribe',translation:'gpt-4.1-mini',hermes:'等待連接'}};
const roleItems=roles.map(r=>({value:r,label:r}));
const DEMO={zh:'先把注意力帶回來，覺察此刻的呼吸。',en:'Bring your attention back and notice your breathing in this moment.'};
type Draft={text:string;translation:string;preset?:boolean};
const emptyDrafts:Record<Direction,Draft>={'zh-en':{text:'',translation:''},'en-zh':{text:'',translation:''}};
function time(n:number){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(Math.floor(n%60)).padStart(2,'0');}
function today(){return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'long',day:'numeric'}).format(new Date());}
function sourceOf(s:Segment){return s.direction==='en-zh'?s.en:s.zh;}
function targetOf(s:Segment){return s.direction==='en-zh'?s.zh:s.en;}
async function response<T>(r:Response):Promise<T>{const body:unknown=await r.json();if(!r.ok){const message=body&&typeof body==='object'&&'error' in body&&typeof body.error==='string'?body.error:'操作失敗，請稍後重試。';throw new Error(message);}return body as T;}
function message(e:unknown,fallback:string){return e instanceof Error?e.message:fallback;}

export default function Workspace(){
 const [data,setData]=useState<State>(EMPTY),[sessionId,setSessionId]=useState(''),[tab,setTab]=useState('live'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [personId,setPersonId]=useState('none'),[role,setRole]=useState('講者'),[auto,setAuto]=useState(true),[mode,setMode]=useState<'class'|'conversation'>('class'),[direction,setDirection]=useState<Direction>('zh-en'),[formDirection,setFormDirection]=useState<Direction>('zh-en');
 const [recording,setRecording]=useState(false),[starting,setStarting]=useState(false),[processing,setProcessing]=useState(0),[elapsed,setElapsed]=useState(0),[level,setLevel]=useState(0),[demo,setDemo]=useState(false),[projected,setProjected]=useState(false),[large,setLarge]=useState(false),[speaking,setSpeaking]=useState(false);
 const [dialog,setDialog]=useState<'session'|'sessionEdit'|'person'|'segment'|'memory'|null>(null),[editPerson,setEditPerson]=useState<Person|null>(null),[editSegment,setEditSegment]=useState<Segment|null>(null),[editMemory,setEditMemory]=useState<Memory|null>(null);
 const [name,setName]=useState(''),[topic,setTopic]=useState(''),[notes,setNotes]=useState(''),[zh,setZh]=useState(''),[en,setEn]=useState(''),[meaning,setMeaning]=useState(''),[context,setContext]=useState(''),[remember,setRemember]=useState(false),[formPerson,setFormPerson]=useState('none'),[formRole,setFormRole]=useState('講者');
 const [query,setQuery]=useState(''),[memoryFilter,setMemoryFilter]=useState<'all'|'candidate'|'verified'>('all'),[samplePerson,setSamplePerson]=useState(''),[sampleSeconds,setSampleSeconds]=useState(5),[voiceAvailable,setVoiceAvailable]=useState(false),[translatedOnly,setTranslatedOnly]=useState(false);
 const [theme,setTheme]=useState<'sky'|'wood'>('sky'),[composerOpen,setComposerOpen]=useState(false),[replyTo,setReplyTo]=useState<Segment|null>(null);
 const [sessionDrafts,setDrafts]=useState<Record<string,Record<Direction,Draft>>>({});
 const composerInput=useRef<HTMLTextAreaElement|null>(null),draft=(sessionDrafts[sessionId]??emptyDrafts)[direction];
 const recorder=useRef<Capture|null>(null),sampleRecorder=useRef<Capture|null>(null),sampleTimer=useRef<ReturnType<typeof setInterval>|null>(null),sampleCancelled=useRef(false),queue=useRef(Promise.resolve()),pending=useRef(0),started=useRef(0),config=useRef({sessionId:'',personId:'none',role:'講者',auto:true,direction:'zh-en' as Direction});
 const mounted=useRef(true),loadSequence=useRef(0),sampleStarting=useRef(false);
 config.current={sessionId,personId,role,auto:mode==='conversation'?false:auto,direction};
 const session=data.sessions.find(s=>s.id===sessionId),last=data.segments.at(-1),person=data.people.find(p=>p.id===personId),verified=data.memories.filter(m=>m.status==='verified'),candidates=data.memories.filter(m=>m.status==='candidate');
 const sessionLocked=recording||starting||processing>0||!!samplePerson;
 const peopleItems=[{value:'none',label:'暫不指定'},...data.people.map(p=>({value:p.id,label:p.name}))];
 const shownDirection=demo?direction:last?.direction??direction;
 const sourceText=demo?(shownDirection==='zh-en'?DEMO.zh:DEMO.en):last?sourceOf(last):'';
 const targetText=demo?(shownDirection==='zh-en'?DEMO.en:DEMO.zh):last?targetOf(last):'';
 const shownMemories=data.memories.filter(m=>(memoryFilter==='all'||m.status===memoryFilter)&&(!query.trim()||[m.zh,m.en,m.meaning,m.context,data.people.find(p=>p.id===m.person_id)?.name??''].join(' ').toLowerCase().includes(query.toLowerCase().trim())));

 const load=useCallback(async(sid?:string)=>{const sequence=++loadSequence.current;try{const r=await fetch('/api/workspace'+(sid?'?session='+encodeURIComponent(sid):''));const body=await response<State>(r);if(!mounted.current||sequence!==loadSequence.current)return;setData(body);setError('');setSessionId(body.sessionId??'');}catch(e){if(mounted.current&&sequence===loadSequence.current)setError(message(e,'無法載入資料。'));}finally{if(mounted.current&&sequence===loadSequence.current)setLoading(false);}},[]);
 useEffect(()=>{mounted.current=true;void load();setVoiceAvailable('speechSynthesis' in window);return ()=>{mounted.current=false;recorder.current?.stop();sampleCancelled.current=true;sampleRecorder.current?.stop();if(sampleTimer.current)clearInterval(sampleTimer.current);window.speechSynthesis?.cancel();};},[load]);
 useEffect(()=>{try{if(localStorage.getItem('zen-bridge-theme')==='wood')setTheme('wood');}catch{}},[]);
 useEffect(()=>{setReplyTo(null);},[sessionId]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>setElapsed((Date.now()-started.current)/1000),500);return ()=>clearInterval(timer);},[recording]);
 useEffect(()=>{if(recording&&speaking){window.speechSynthesis?.cancel();setSpeaking(false);}},[recording,speaking]);
 const post=async(payload:unknown)=>{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return response<{id:string}>(r);};
 const action=async(payload:unknown,success:string,sid=sessionId)=>{setBusy(true);try{const result=await post(payload);await load(sid);toast.success(success);return result;}catch(e){toast.error(message(e,'儲存失敗。'));return null;}finally{setBusy(false);}};
 const stop=useCallback(()=>{const current=recorder.current;recorder.current=null;current?.stop();setRecording(false);},[]);
 async function start(d:Direction=direction){
  if(starting||samplePerson||recording)return;
  if(!data.connection.openai){toast.info('語音翻譯尚未連接，可以先使用文字紀錄。');return;}
  if(!sessionId){open('session');return;}
  if(session?.status==='finished'){toast.info('這場社課已結束，請建立新活動。');return;}
  if(!navigator.mediaDevices?.getUserMedia){toast.error('無法使用麥克風，請改用支援的瀏覽器或文字輸入。');return;}
  window.speechSynthesis?.cancel();document.querySelectorAll('audio').forEach(a=>a.pause());setSpeaking(false);setDirection(d);config.current={...config.current,direction:d,auto:mode==='conversation'?false:auto};setDemo(false);setElapsed(0);setStarting(true);started.current=Date.now();
  try{recorder.current=await capture((blob,offset)=>{
   if(!mounted.current)return;const snapshot={...config.current};
   if(pending.current>=3){toast.error('處理速度暫時跟不上，已暫停收音。請等字幕完成後繼續。');stop();return;}
   pending.current++;setProcessing(pending.current);
   queue.current=queue.current.then(async()=>{try{const f=new FormData();f.set('audio',blob,'speech.wav');f.set('sessionId',snapshot.sessionId);f.set('personId',snapshot.personId==='none'?'':snapshot.personId);f.set('role',snapshot.role);f.set('auto',String(snapshot.auto));f.set('direction',snapshot.direction);f.set('offset',String(offset));const r=await fetch('/api/audio',{method:'POST',body:f,signal:AbortSignal.timeout(180000)});await response<{ids:string[]}>(r);await load(snapshot.sessionId);}catch(e){if(mounted.current){toast.error(message(e,'語音處理失敗，請稍後再試。'));stop();}}finally{pending.current--;if(mounted.current)setProcessing(pending.current);}});
  },setLevel);if(!mounted.current){recorder.current.stop();recorder.current=null;}else setRecording(true);}catch{toast.error('請允許麥克風權限，或改用文字輸入。');}finally{setStarting(false);}
 }
 function choosePerson(id:string){recorder.current?.flush();const p=data.people.find(x=>x.id===id),currentRole=(session&&JSON.parse(session.roles)[id])??p?.role??'講者';config.current={...config.current,personId:id,role:currentRole,auto:false};setPersonId(id);setRole(currentRole);setAuto(false);}
 function changeMode(v:'class'|'conversation'){if(sessionLocked||busy)return;setMode(v);setDirection('zh-en');config.current={...config.current,direction:'zh-en',auto:v==='class'?auto:false};setComposerOpen(v==='conversation');setReplyTo(null);setDemo(false);}
 function changeTheme(v:'sky'|'wood'){setTheme(v);try{localStorage.setItem('zen-bridge-theme',v);}catch{}}
 function updateDraft(field:'text'|'translation',value:string){setDrafts(old=>{const pair=old[sessionId]??emptyDrafts,current=pair[direction];return {...old,[sessionId]:{...pair,[direction]:{...current,...(field==='text'&&current.preset?{translation:''}:{}),[field]:value,preset:false}}};});}
 function compose(d:Direction=direction,s?:Segment){
  if(sessionLocked||busy||session?.status==='finished')return;
  if(s){setMode('conversation');setReplyTo(s);}else setReplyTo(null);
  setDirection(d);config.current={...config.current,direction:d,auto:mode==='conversation'||s?false:auto};setComposerOpen(true);
  if(!sessionId){open('session');return;}
  requestAnimationFrame(()=>{composerInput.current?.focus({preventScroll:true});composerInput.current?.scrollIntoView({behavior:'smooth',block:'nearest'});});
 }
 async function sendDraft(){
  if(busy||sessionLocked||!sessionId||session?.status==='finished'||!draft.text.trim())return;
  const sentSession=sessionId,sentDirection=direction,sentDraft={...draft};const result=await action({action:'segment',sessionId:sentSession,personId:personId==='none'?null:personId,role,direction:sentDirection,zh:sentDirection==='zh-en'?sentDraft.text:sentDraft.translation,en:sentDirection==='en-zh'?sentDraft.text:sentDraft.translation,note:'',translate:data.connection.openai&&!sentDraft.translation.trim()},'這一句已保存。');
  if(result){setDrafts(old=>({...old,[sentSession]:{...(old[sentSession]??emptyDrafts),[sentDirection]:{text:'',translation:''}}}));setReplyTo(null);setDemo(false);}
 }
 function open(kind:'session'|'sessionEdit'|'person'|'segment'|'memory',p?:Person,s?:Segment,m?:Memory){
  setDialog(kind);setEditPerson(p??null);setEditSegment(s??null);setEditMemory(m??null);setName(kind==='session'?today()+'社課':kind==='sessionEdit'?session?.title??'':p?.name??'');setTopic(kind==='sessionEdit'?session?.topic??'':'');setNotes(kind==='sessionEdit'?session?.notes??'':p?.notes??'');setZh(s?.zh??m?.zh??'');setEn(s?.en??m?.en??'');setMeaning(s?.note??m?.meaning??'');setContext(m?.context??session?.topic??'');setRemember(false);setFormPerson(s?.person_id??m?.person_id??(kind==='segment'?personId:'none'));setFormRole(p?.role??s?.role??m?.role??(kind==='memory'?'通用':role));setFormDirection(s?.direction??direction);
 }
 async function submit(translate=false){
  if(dialog==='session'||dialog==='sessionEdit'){setBusy(true);try{const r=await post({action:dialog==='sessionEdit'?'editSession':'session',sessionId,title:name,topic,notes});await load(r.id);setDialog(null);setTab('live');toast.success(dialog==='sessionEdit'?'社課背景已更新。':'社課已建立，準備好就能開始。');}catch(e){toast.error(message(e,'儲存失敗。'));}finally{setBusy(false);}return;}
  let payload:unknown;
  if(dialog==='person')payload={action:'person',id:editPerson?.id,name,role:formRole,notes};
  else if(dialog==='memory')payload={action:editMemory?'editMemory':'memory',id:editMemory?.id,personId:formPerson==='none'?null:formPerson,role:formRole,zh,en,meaning,context};
  else if(editSegment)payload={action:'correct',id:editSegment.id,personId:formPerson==='none'?null:formPerson,role:formRole,zh,en,note:meaning,remember};
  else payload={action:'segment',sessionId,personId:formPerson==='none'?null:formPerson,role:formRole,direction:formDirection,zh,en,note:meaning,translate};
  if(await action(payload,dialog==='memory'?'例句已保存，確認後可供翻譯參考。':'這一句已保存。')){setDialog(null);setDemo(false);}
 }
 async function saveReference(p:Person,blob:Blob,duration:number){const f=new FormData();f.set('audio',blob,'voice.'+(blob.type.includes('wav')?'wav':'audio'));f.set('personId',p.id);f.set('duration',String(duration));await response<{ok:boolean}>(await fetch('/api/reference',{method:'POST',body:f}));await load(sessionId);}
 async function uploadReference(p:Person,file:File){setBusy(true);let url='';try{url=URL.createObjectURL(file);const duration=await new Promise<number>((resolve,reject)=>{const audio=new Audio(url);const t=setTimeout(()=>reject(new Error('無法讀取長度，請改用 WAV 或直接錄製。')),7000);audio.onloadedmetadata=()=>{clearTimeout(t);resolve(audio.duration);};audio.onerror=()=>{clearTimeout(t);reject(new Error('無法讀取聲音檔。'));};});if(duration<2||duration>10||!Number.isFinite(duration))throw new Error('請選擇 2–10 秒的聲音樣本，或直接錄製 5 秒。');await saveReference(p,file,duration);toast.success('聲音樣本已保存。');}catch(e){toast.error(message(e,'聲音樣本無法讀取。'));}finally{if(url)URL.revokeObjectURL(url);setBusy(false);}}
 async function recordSample(p:Person){
  if(sampleStarting.current||samplePerson||sessionLocked)return;sampleStarting.current=true;sampleCancelled.current=false;setSamplePerson(p.id);setSampleSeconds(5);setBusy(true);
  window.speechSynthesis?.cancel();document.querySelectorAll('audio').forEach(a=>a.pause());setSpeaking(false);
  try{sampleRecorder.current=await capture((blob)=>{if(sampleCancelled.current||!mounted.current)return;void (async()=>{try{const b=await blob.arrayBuffer(),duration=(b.byteLength-44)/(2*new DataView(b).getUint32(24,true));if(duration<2)throw new Error('錄音太短，請重新錄製。');await saveReference(p,blob,duration);toast.success(p.name+'的聲音樣本已保存。');}catch(e){toast.error(message(e,'聲音樣本儲存失敗。'));}finally{setSamplePerson('');setBusy(false);}})();},()=>{});
   if(!mounted.current||sampleCancelled.current){sampleCancelled.current=true;sampleRecorder.current.stop();sampleRecorder.current=null;return;}let count=5;sampleTimer.current=setInterval(()=>{count--;setSampleSeconds(count);if(count<=0){if(sampleTimer.current)clearInterval(sampleTimer.current);sampleTimer.current=null;sampleRecorder.current?.stop();sampleRecorder.current=null;}},1000);
  }catch{setSamplePerson('');setBusy(false);toast.error('請允許麥克風權限，或上傳聲音檔。');}finally{sampleStarting.current=false;}
 }
 function cancelSample(){sampleCancelled.current=true;if(sampleTimer.current)clearInterval(sampleTimer.current);sampleTimer.current=null;sampleRecorder.current?.stop();sampleRecorder.current=null;setSamplePerson('');setBusy(false);}
 function readAloud(text:string,lang:string){
  if(!voiceAvailable){toast.info('此瀏覽器不支援朗讀，請查看字幕。');return;}
  if(recording||starting||samplePerson){toast.info('請先停止收音，再播放朗讀。');return;}
  if(speaking){window.speechSynthesis.cancel();setSpeaking(false);return;}
  const synth=window.speechSynthesis,utterance=new SpeechSynthesisUtterance(text);utterance.lang=lang;utterance.rate=.94;const voices=synth.getVoices();utterance.voice=voices.find(v=>v.lang.toLowerCase()===lang.toLowerCase())??voices.find(v=>v.lang.toLowerCase().startsWith(lang.slice(0,2)))??null;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>{setSpeaking(false);toast.info('目前的裝置無法朗讀這段內容，請查看字幕。');};synth.cancel();synth.speak(utterance);setSpeaking(true);
 }
 async function copyText(text:string){try{await navigator.clipboard.writeText(text);toast.success('已複製。');}catch{toast.info('無法使用剪貼簿，請直接選取文字複製。');}}
 function endSession(){window.speechSynthesis?.cancel();setSpeaking(false);if(sessionId)void action({action:'finish',sessionId},'這場社課已結束，紀錄已保存。');}
 useEffect(()=>{
  const mc=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!mc)return;const life=new AbortController();const register=(tool:unknown)=>{try{void Promise.resolve(mc.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
  register({name:'read_translation_workspace',description:'Read this classroom workspace and refresh visible records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{await load(sessionId);return response<State>(await fetch('/api/workspace'+(sessionId?'?session='+sessionId:'')));}});
  register({name:'propose_translation_example',description:'Save a candidate bilingual example and refresh the memory list. Does not verify it.',inputSchema:{type:'object',properties:{zh:{type:'string'},en:{type:'string'},meaning:{type:'string'},context:{type:'string'}},required:['zh','en','meaning','context'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:Record<string,unknown>)=>{if(!['zh','en','meaning','context'].every(k=>typeof input[k]==='string'&&String(input[k]).trim()))throw new Error('請提供中文、英文、原意與情境。');const r=await post({action:'memory',...input,personId:null,role:'通用'});await load(sessionId);return r;}});
  return ()=>life.abort();
 },[load,sessionId]);

 return <div className={'zen-app theme-'+theme+' page-'+tab+' '+(projected?'projected ':'')+(large?'large-type':'')}>
 <Toaster richColors position="top-center"/>
 <Tabs value={tab} onValueChange={v=>{if(recording||starting||samplePerson){toast.info('請先停止收音，再切換頁面。');return;}setTab(v);}} className="app-layout">
 <aside className="navigation"><div className="nav-brand"><Turtle/><div><strong>禪譯</strong><small>Zen Bridge</small></div></div><TabsList className="nav-tabs"><TabsTrigger value="live"><MessageCircle/><span>現場翻譯</span></TabsTrigger><TabsTrigger value="people"><Users/><span>講者資料</span></TabsTrigger><TabsTrigger value="memory"><NotebookPen/><span>翻譯筆記</span></TabsTrigger><TabsTrigger value="connections"><Settings2/><span>連線設定</span></TabsTrigger></TabsList><div className="nav-bottom">淡江禪學社</div></aside>
 <main className="desk">
 <header className="club-header"><img className="terrace" src="/art/terrace-banner.png" alt="" width={2171} height={724}/><div className="header-paper"><div><p className="club-name">淡江大學・禪學社</p><h1>{tab==='live'?'社課翻譯':tab==='people'?'一起說話的夥伴':tab==='memory'?'我們的翻譯小冊':'語音與記憶連接'}</h1><p className="header-caption">{tab==='live'?'Chinese & English':tab==='people'?'聲音樣本・角色・常用語':tab==='memory'?'記下原意，留給下一次社課。':'確認服務狀態與裝置朗讀。'}</p></div></div><div className="header-tools"><label className="theme-choice"><span>風景</span><Picker value={theme} onChange={v=>changeTheme(v as 'sky'|'wood')} items={[{value:'sky',label:'晴空'},{value:'wood',label:'木緣'}]} label="選擇畫面風格"/></label><button className="header-refresh" onClick={()=>load(sessionId)} aria-label="重新載入資料" disabled={busy||sessionLocked}><RefreshCw size={17}/></button></div></header>
 {error&&<div className="error-banner" role="alert"><Info size={18}/><span>{error}</span><Button variant="outline" onClick={()=>load(sessionId)}>重試</Button></div>}
 <div className="session-toolbar"><div className="session-picker"><FileText size={18}/>{data.sessions.length?<Picker label="本次社課" disabled={sessionLocked||busy} value={sessionId} onChange={id=>{setDemo(false);void load(id);}} items={data.sessions.map(s=>({value:s.id,label:s.title+(s.status==='finished'?' · 已結束':'')}))}/>:<span>{loading?'正在讀取社課…':'今天的社課還沒建立'}</span>}</div><div className="session-tools">{session&&<span className="save-note">{session.status==='finished'?'已結束 · 已保存':'紀錄自動保存'}</span>}<Button variant="outline" disabled={sessionLocked||loading||busy} onClick={()=>open('session')}><Plus size={16}/><span>{session?'新社課':'建立社課'}</span></Button></div></div>
 <TabsContent value="live" className="page-content">
 <div className="translation-layout"><section className="translation-main">
 <div className="mode-row"><div className="mode-picker" aria-label="使用模式"><button disabled={sessionLocked} aria-pressed={mode==='class'} className={mode==='class'?'selected':''} onClick={()=>changeMode('class')}><Headphones size={17}/>社課翻譯</button><button disabled={sessionLocked} aria-pressed={mode==='conversation'} className={mode==='conversation'?'selected':''} onClick={()=>changeMode('conversation')}><ArrowLeftRight size={17}/>雙向對話</button></div><div className="reading-tools"><button onClick={()=>setLarge(!large)} aria-label="切換大字" aria-pressed={large}><span>大字</span></button><button onClick={()=>setProjected(!projected)} aria-label={projected?'結束投影模式':'開啟投影模式'}>{projected?<Minimize2 size={18}/>:<Maximize2 size={18}/>}<span>{projected?'返回':'投影'}</span></button></div></div>
 <section className={'capture-controls mode-'+mode} aria-label="收音與發言">
 <div className="capture-top"><div className="capture-description"><span className={'mic-mark '+(recording?'listening':'')}><Mic size={19}/></span><div><strong>{recording?(direction==='zh-en'?'正在聆聽中文':'Listening in English'):processing?'正在處理剛才的發言':mode==='class'?'準備開始社課':'輪到誰，就選哪個語言'}</strong><p>{mode==='class'?'每 8 秒更新一段字幕，也可以手動選擇講者。':'同一裝置輪流發言。說完按停止，再換另一位。'}</p></div></div><span className="control-clock">{time(elapsed)}</span></div>
 <div className="inline-speaker"><Users size={16}/><Picker value={personId} onChange={choosePerson} items={peopleItems} label="這一句的說話者" disabled={busy||starting||processing>0&&!recording}/><span>{mode==='class'&&auto?'自動辨識・可手動接管':person?.name?role:'不指定也可以'}</span><div className="sound-meter" aria-label={'麥克風音量 '+Math.round(level*100)+'%'}>{Array.from({length:9},(_,i)=><i key={i} style={{height:recording?7+Math.min(25,level*36)*(0.4+(i%3)*.3):7}}/>)}</div></div>
 {mode==='class'?<div className="microphone-buttons"><Button className={'record-button '+(recording?'record-stop':'')} disabled={!recording&&(!data.connection.openai||busy||starting||processing>0||!!samplePerson||session?.status==='finished')} onClick={()=>recording?stop():void start('zh-en')}>{recording?<><Square size={18}/>停止收音</>:<><Mic size={19}/>{starting?'開啟中…':data.connection.openai?'開始收音':'語音尚未接通'}</>}</Button><Button variant={data.connection.openai?'outline':'default'} className="type-button" disabled={loading||busy||sessionLocked||session?.status==='finished'} onClick={()=>compose('zh-en')}><Keyboard size={18}/>用文字說一句</Button></div>:<div className="turn-lanes">
 <div className={'turn-lane chinese-lane '+(direction==='zh-en'?'current-turn':'')}><div className="turn-heading"><span>中</span><strong>我說中文</strong><small>Chinese to English</small></div><div className="turn-actions"><Button className={'record-button '+(recording&&direction==='zh-en'?'record-stop':'')} disabled={recording?direction!=='zh-en':!data.connection.openai||busy||starting||processing>0||session?.status==='finished'} onClick={()=>recording?stop():void start('zh-en')}>{recording&&direction==='zh-en'?<><Square size={16}/>說完了，停止</>:<><Mic size={17}/>中文收音</>}</Button><Button variant="ghost" disabled={busy||sessionLocked||session?.status==='finished'} onClick={()=>compose('zh-en')}><Keyboard size={16}/>中文打字</Button></div></div>
 <div className={'turn-lane english-lane '+(direction==='en-zh'?'current-turn':'')}><div className="turn-heading"><span>EN</span><strong>I speak English</strong><small>English to Chinese</small></div><div className="turn-actions"><Button className={'record-button english-button '+(recording&&direction==='en-zh'?'record-stop':'')} disabled={recording?direction!=='en-zh':!data.connection.openai||busy||starting||processing>0||session?.status==='finished'} onClick={()=>recording?stop():void start('en-zh')}>{recording&&direction==='en-zh'?<><Square size={16}/>Stop listening</>:<><Mic size={17}/>Speak English</>}</Button><Button variant="ghost" disabled={busy||sessionLocked||session?.status==='finished'} onClick={()=>compose('en-zh')}><Keyboard size={16}/>Type in English</Button></div></div>
 </div>}
 </section>
 {(composerOpen||mode==='conversation')&&<form className={'inline-composer composer-'+direction} onSubmit={e=>{e.preventDefault();void sendDraft();}}><div className="composer-heading"><div><Keyboard size={17}/><strong>{direction==='zh-en'?'用中文說一句':'Type your message in English'}</strong></div><button type="button" disabled={busy||sessionLocked} onClick={()=>{setComposerOpen(false);if(mode==='conversation')changeMode('class');}} aria-label="收起文字輸入"><X size={17}/></button></div>
 {replyTo&&<div className="reply-context"><Reply size={16}/><div><small>{direction==='en-zh'?'Replying to ':'回覆 '}{replyTo.label}</small><p>{sourceOf(replyTo)}</p></div><button type="button" onClick={()=>setReplyTo(null)} aria-label="取消回覆對象"><X size={15}/></button></div>}
 <Textarea ref={composerInput} aria-label={direction==='zh-en'?'中文發言原文':'English message'} lang={direction==='zh-en'?'zh-Hant':'en'} value={draft.text} onChange={e=>updateDraft('text',e.target.value)} placeholder={direction==='zh-en'?'想說什麼，慢慢寫下來。':'What would you like to say or ask?'} maxLength={8000} rows={3} disabled={!sessionId||busy||sessionLocked||session?.status==='finished'} required/>
 <div className="phrase-choices"><span>{direction==='zh-en'?'也可以這樣說':'Useful phrases'}</span>{[{zh:'可以再說一次嗎？',en:'Could you say that again?'},{zh:'我想請問一個問題。',en:'I have a question.'},{zh:'謝謝你的分享。',en:'Thank you for sharing.'}].map(x=><button key={x.en} type="button" disabled={!sessionId||busy||sessionLocked||session?.status==='finished'} onClick={()=>setDrafts(old=>({...old,[sessionId]:{...(old[sessionId]??emptyDrafts),[direction]:{text:direction==='zh-en'?x.zh:x.en,translation:direction==='zh-en'?x.en:x.zh,preset:true}}}))}>{direction==='zh-en'?x.zh:x.en}</button>)}</div>
 <details className="manual-translation" open={!data.connection.openai}><summary>{direction==='zh-en'?'補上英文譯文（選填）':'Add a Chinese translation (optional)'}</summary><Textarea aria-label={direction==='zh-en'?'手動英文譯文':'手動中文譯文'} lang={direction==='zh-en'?'en':'zh-Hant'} value={draft.translation} onChange={e=>updateDraft('translation',e.target.value)} rows={2} maxLength={8000} disabled={!sessionId||busy||sessionLocked||session?.status==='finished'} placeholder={direction==='zh-en'?'已確認的英文，可以直接填在這裡。':'Add the Chinese translation if you already know it.'}/></details>
 <div className="composer-footer"><span>{!sessionId?'先建立社課，內容會保存在同一場活動。':direction==='en-zh'?(data.connection.openai?'An empty translation will be translated when you save.':'Automatic translation is not connected. You can save your text and add a Chinese translation.'):(data.connection.openai?'未填譯文時會自動翻譯，再保存。':'語音翻譯尚未連接；可以先保存文字與手動譯文。')}</span>{!sessionId?<Button type="button" disabled={loading||busy} onClick={()=>open('session')}><Plus size={16}/>建立社課</Button>:<Button type="submit" disabled={busy||sessionLocked||!draft.text.trim()||session?.status==='finished'}><Send size={16}/>{direction==='en-zh'?(busy?'Saving…':data.connection.openai&&!draft.translation.trim()?'Translate & save':'Save message'):(busy?'保存中…':data.connection.openai&&!draft.translation.trim()?'翻譯並保存':'保存這一句')}</Button>}</div></form>}

 <section className="translation-paper" aria-label="中英字幕"><div className="paper-top"><div className="paper-label"><TurtleMood pose={recording?'listen':speaking?'speak':processing?'notes':'wave'} className="paper-mascot" alt=""/><span className="stamp">{mode==='class'?'社課札記':'Conversation'}</span><span className="capture-state" role="status">{demo?'試看範例':recording?'正在聆聽':starting?'正在開啟麥克風':processing?'正在辨識與翻譯':'準備好了'}</span></div><span className="paper-direction">{shownDirection==='zh-en'?'中 → EN':'EN → 中'}</span></div>
 {!last&&!demo?<div className="welcome-sheet"><TurtleMood pose="wave" className="welcome-turtle"/><div><span className="handwritten">龜龜陪你一起聽。</span><h2>{session?'第一句話，留在這裡':'先為今天的社課開一頁'}</h2><p>{mode==='conversation'?'兩個語言，輪流說一句。英文提問也能翻成中文。':'選擇講者、按下收音，中英字幕會留在這裡。'}</p>{!session?<Button disabled={loading} onClick={()=>open('session')}><Plus size={16}/>建立今天的社課</Button>:<button className="text-link" onClick={()=>setDemo(true)}>試看一段字幕</button>}</div></div>:<div className={'subtitle-spread '+(translatedOnly?'translated-only':'')} aria-live="polite"><article className="source-page"><div className="language-heading"><span>{shownDirection==='zh-en'?'中文・原文':'English · Original'}</span><small>{shownDirection==='zh-en'?'CHINESE':'英文原文'}</small></div><p lang={shownDirection==='zh-en'?'zh-Hant':'en'}>{sourceText||'原文尚未完成'}</p></article><article className="translated-page"><div className="language-heading"><span>{shownDirection==='zh-en'?'English · Translation':'中文・翻譯'}</span><small>{shownDirection==='zh-en'?'英文翻譯':'TRADITIONAL CHINESE'}</small></div><p lang={shownDirection==='zh-en'?'en':'zh-Hant'}>{targetText||'翻譯尚未完成，可以手動補上。'}</p></article></div>}
 <div className="paper-bottom"><span>{demo?'範例不會加入社課或記憶':last?last.label+' · '+last.role:'龜龜的社課小冊・中英字幕'}</span><div className="paper-actions">{(last||demo)&&<><button disabled={!targetText||recording||!!samplePerson||!voiceAvailable} onClick={()=>readAloud(targetText,shownDirection==='zh-en'?'en-US':'zh-TW')}><Volume2 size={16}/>{speaking?'停止朗讀':'朗讀譯文'}</button><button disabled={!targetText} onClick={()=>copyText(targetText)} aria-label="複製譯文"><Copy size={16}/></button></>}{last&&!demo&&<button onClick={()=>open('segment',undefined,last)}><Edit3 size={15}/>修正</button>}</div></div></section>

 {!data.connection.openai&&<div className="service-notice"><Info size={16}/><p>語音翻譯尚未連接。先建立社課、用文字保存中英內容也可以。</p><button onClick={()=>setTab('connections')}>查看設定</button></div>}
 <section className="conversation-notebook"><div className="section-heading"><div><h2>{mode==='conversation'?'你一句，我一句':'這場社課的紀錄'} <span className="count">{data.segments.length}</span></h2><p>{mode==='conversation'?'中文發言與英文提問，依時間放在一起。':'最初內容與每次修正，都會保留下來。'}</p></div><Button variant="ghost" disabled={!sessionId} onClick={()=>window.location.assign('/api/export?session='+sessionId)} aria-label="匯出本場社課"><Download size={18}/></Button></div>
 {!data.segments.length?<div className="notebook-empty"><span className="empty-line"/><p>第一句話，從這裡開始。</p><button disabled={!sessionId||busy} onClick={()=>compose()}>先用文字記下一句</button>{demo&&<button onClick={()=>setDemo(false)}>收起範例</button>}</div>:<div className={'conversation-list '+(mode==='conversation'?'bubble-list':'')}>
 {data.segments.slice().reverse().map(s=><article className={'utterance '+(s.direction==='en-zh'?'from-english':'from-chinese')} key={s.id}><div className="utterance-meta"><span className="speaker-initial">{s.label.slice(-2)}</span><strong>{s.label}</strong><span>{s.direction==='en-zh'?'EN → 中':'中 → EN'}</span><time>{new Intl.DateTimeFormat('zh-TW',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Taipei'}).format(new Date(s.created_at))}</time><button onClick={()=>open('segment',undefined,s)} aria-label={'修正 '+sourceOf(s)}><Edit3 size={15}/></button></div><p className="utterance-source" lang={s.direction==='en-zh'?'en':'zh-Hant'}>{sourceOf(s)||'原文尚未完成'}</p><p className="utterance-target" lang={s.direction==='en-zh'?'zh-Hant':'en'}>{targetOf(s)||'待補譯文'}</p>{s.note&&<p className="utterance-note">{s.note}</p>}<div className="utterance-actions"><button disabled={busy||sessionLocked||session?.status==='finished'} onClick={()=>compose(s.direction==='en-zh'?'zh-en':'en-zh',s)}><Reply size={14}/>{s.direction==='en-zh'?'用中文回覆':'Reply in English'}</button><button disabled={recording||!!samplePerson||!voiceAvailable||!targetOf(s)} onClick={()=>readAloud(targetOf(s),s.direction==='en-zh'?'zh-TW':'en-US')}><Volume2 size={14}/>朗讀</button><button onClick={()=>copyText([s.zh,s.en].filter(Boolean).join('\n'))}><Copy size={14}/>複製</button></div></article>)}
 </div>}</section>
 </section>
 <aside className="class-sidebar"><section className="companion-note"><TurtleMood pose={recording?'listen':speaking?'speak':'notes'} alt=""/><div><span className="handwritten">龜龜的小冊</span><p>{recording?'我在聽，慢慢說。':speaking?'正在朗讀譯文。':'今天的每一句，都放在這裡。'}</p><small>{data.segments.length} 段紀錄 · {verified.length} 句已確認</small></div></section><section className="speaker-note"><div className="note-title"><span className="note-number">01</span><h2>{mode==='conversation'?'這一句是誰說的？':'現在的講者'}</h2></div>{mode==='class'&&<label className="auto-choice"><span>自動辨識講者</span><Switch checked={auto} onCheckedChange={v=>{recorder.current?.flush();config.current={...config.current,auto:v};setAuto(v);}} aria-label="自動辨識講者"/></label>}<div className="current-speaker"><span className="person-avatar">{mode==='class'&&auto?<Users size={22}/>:person?.name.slice(-2)||'？'}</span><div><strong>{mode==='class'&&auto?(last?.label??'等你開口'):person?.name??'不指定也可以'}</strong><small>{mode==='class'&&auto?'也可以手動選擇':role}</small></div></div><label className="field-label">{mode==='class'&&auto?'手動接管':'說話的人'}<Picker value={personId} onChange={choosePerson} items={peopleItems} label="選擇說話者"/></label><label className="field-label">這場的角色<Picker value={role} onChange={r=>{recorder.current?.flush();config.current={...config.current,role:r};setRole(r);if(personId!=='none'&&sessionId)void action({action:'sessionRole',sessionId,personId,role:r},'本場角色已更新。');}} items={roleItems} label="本場角色"/></label>{data.people.length>0&&<div className="quick-people">{data.people.slice(0,4).map(p=><button key={p.id} className={personId===p.id?'chosen':''} onClick={()=>choosePerson(p.id)}>{p.name}</button>)}</div>}<button className="text-link" disabled={recording||starting} onClick={()=>setTab('people')}>管理夥伴與聲音</button></section>
 <section className="lesson-note"><div className="note-title"><span className="note-number">02</span><h2>今天的背景</h2></div><h3>{session?.topic||session?.title||'還沒有建立社課'}</h3>{session&&<button className="edit-context text-link" disabled={sessionLocked||busy} onClick={()=>open('sessionEdit')}><Edit3 size={14}/>補充主題與講義</button>}<p>{session?.notes||'建立社課時，可加入主題與講義，讓翻譯多一點上下文。'}</p>{session&&<Button variant="outline" className="finish-button" disabled={sessionLocked||busy||session.status==='finished'} onClick={endSession}>{session.status==='finished'?<><CheckCircle2 size={16}/>這場已保存</>:'結束這場社課'}</Button>}</section>
 <section className="little-note"><TurtleMood pose="notes" alt=""/><div><strong>記得這一句</strong><p>{verified.length} 個已確認例句</p><button className="text-link" disabled={recording||starting} onClick={()=>setTab('memory')}>翻翻我們的筆記</button></div></section>
 <label className="display-option"><Checkbox checked={translatedOnly} onCheckedChange={v=>setTranslatedOnly(v===true)}/><span>字幕只看翻譯</span></label>
 </aside></div>
 </TabsContent>
 <TabsContent value="people" className="page-content"><section className="collection-paper people-paper"><div className="section-heading"><div><h2>講者、主持人與分享的夥伴</h2><p>錄 5 秒清楚的聲音，之後可用來辨識講者。</p></div><Button onClick={()=>open('person')} disabled={busy}><Plus size={16}/>新增夥伴</Button></div><div className="help-strip"><span className="pencil-number">1</span><p>加入姓名</p><span className="pencil-number">2</span><p>直接錄聲音</p><span className="pencil-number">3</span><p>勾選本場講者（最多 4 位）</p></div>
 {!data.people.length?<div className="collection-empty"><TurtleMood pose="listen"/><h3>把一起說話的夥伴加進來</h3><p>可以先填姓名，其他資料慢慢補。</p><Button variant="outline" onClick={()=>open('person')}>新增第一位夥伴</Button></div>:<div className="people-list">{data.people.map((p,i)=><article className="person-row" key={p.id}><span className={'person-avatar tone-'+i%3}>{p.name.slice(-2)}</span><div className="person-info"><div><h3>{p.name}</h3><span className="role-tag">{p.role}</span></div><p>{p.notes||'還沒有填入常用語或比喻。'}</p><span className="reference-note">{p.reference_key?<><CheckCircle2 size={14}/>聲音已保存</>:<><Mic size={14}/>尚未錄製聲音</>}</span>{p.reference_key&&<audio controls preload="none" src={'/api/reference?id='+p.id} aria-label={p.name+'的聲音樣本'}/>}</div><div className="person-actions">{samplePerson===p.id?<div className="sample-recording" role="status"><Mic size={18}/><strong>{sampleSeconds>0?'請自然說話 · '+sampleSeconds+' 秒':'正在保存…'}</strong>{sampleSeconds>0&&<button onClick={cancelSample} aria-label="取消錄製"><X size={16}/></button>}</div>:<><Button variant="outline" disabled={busy||sessionLocked} onClick={()=>recordSample(p)}><Mic size={16}/>{p.reference_key?'重錄 5 秒':'錄 5 秒聲音'}</Button><label className={'file-upload '+(busy?'disabled':'')}>上傳檔案<input type="file" accept="audio/wav,audio/mpeg,audio/mp4,audio/x-m4a,audio/webm,audio/ogg,.m4a" disabled={busy||sessionLocked} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadReference(p,f);e.target.value='';}}/></label></>}{p.reference_key&&sessionId&&<label className="reference-choice"><Checkbox disabled={busy||sessionLocked} checked={JSON.parse(session?.speaker_ids??'[]').includes(p.id)} onCheckedChange={v=>{const selected:string[]=JSON.parse(session?.speaker_ids??'[]');if(v&&selected.length>=4){toast.info('每場最多選 4 位聲音樣本。');return;}void action({action:'sessionSpeakers',sessionId,personIds:v?[...selected,p.id]:selected.filter(id=>id!==p.id)},'本場辨識人員已更新。');}}/><span>本場辨識這位講者</span></label>}</div><button className="row-edit" disabled={busy} onClick={()=>open('person',p)} aria-label={'編輯 '+p.name}><Edit3 size={17}/></button></article>)}</div>}<p className="fine-note">自動辨識最多使用 4 位已知講者；未勾選時使用最早加入樣本的 4 位。無法配對的聲音會標記待確認。上傳檔案須為 2–10 秒、1 MB 以內。</p></section></TabsContent>
 <TabsContent value="memory" className="page-content"><section className="collection-paper memory-ledger"><div className="section-heading"><div><h2>留給下一次社課的理解</h2><p>確認原意之後，翻譯才會參考這份筆記。</p></div><div className="button-group"><Button variant="outline" onClick={()=>window.location.assign('/api/export'+(sessionId?'?session='+sessionId:''))}><Download size={16}/>匯出</Button><Button onClick={()=>open('memory')}><Plus size={16}/>記下一句</Button></div></div><div className="memory-toolbar"><div className="memory-filters">{([{id:'all',label:'全部',count:data.memories.length},{id:'verified',label:'已確認',count:verified.length},{id:'candidate',label:'待確認',count:candidates.length}] as const).map(f=><button key={f.id} className={memoryFilter===f.id?'selected':''} onClick={()=>setMemoryFilter(f.id)}>{f.label}<span>{f.count}</span></button>)}</div><label className="search-field"><Search size={17}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="找中文、英文或講者" aria-label="搜尋翻譯筆記"/></label></div>
 {!shownMemories.length?<div className="collection-empty"><TurtleMood pose="notes"/><h3>{data.memories.length?'沒有找到這一則筆記':'從一個修正開始，慢慢理解'}</h3><p>{data.memories.length?'換個關鍵字，或看看其他分類。':'中文、英文與原意，都可以在這裡留下一份。'}</p></div>:<div className="memory-entries">{shownMemories.map((m,i)=><article className="memory-entry" key={m.id}><span className="entry-index">{String(i+1).padStart(2,'0')}</span><div className="entry-body"><div className="entry-meta"><span className={'memory-status '+m.status}>{m.status==='verified'?<Check size={14}/>:<Edit3 size={14}/>} {m.status==='verified'?'已確認':'待確認'}</span><span>{data.people.find(p=>p.id===m.person_id)?.name??'所有夥伴'} · {m.role} · 第 {m.version} 版</span></div><h3>{m.zh}</h3><p className="entry-english" lang="en">{m.en}</p><dl><div><dt>原意</dt><dd>{m.meaning||'待補充'}</dd></div><div><dt>情境</dt><dd>{m.context||'待補充'}</dd></div></dl><div className="entry-actions"><Button variant="ghost" disabled={busy} onClick={()=>open('memory',undefined,undefined,m)}><Edit3 size={15}/>編輯</Button>{m.status==='candidate'&&<Button variant="outline" disabled={busy} onClick={()=>action({action:'memoryState',id:m.id,status:'verified'},'原意與英文已確認。')}><Check size={16}/>確認這一句</Button>}<button className="quiet-link" disabled={busy} onClick={()=>action({action:'memoryState',id:m.id,status:'archived'},'筆記已封存，不再供翻譯參考。')}>封存</button></div></div></article>)}</div>}<p className="fine-note">每次修正保留版本。Hermes 可查詢與提出候選例句；確認之後才會用於翻譯。目前顯示最近 300 筆，匯出會包含全部例句。</p></section></TabsContent>
 <TabsContent value="connections" className="page-content"><section className="collection-paper settings-paper"><div className="section-heading"><div><h2>語音與記憶的連接</h2><p>這裡的狀態會照實顯示；尚未連接時仍可保存文字。</p></div></div><div className="setting-row"><span className="setting-icon"><Mic size={23}/></span><div><h3>語音辨識</h3><p>中文、英文收音；社課可自動辨識講者。</p><details><summary>查看服務資訊</summary><p>OpenAI · {data.connection.asr}<br/>講者辨識使用 gpt-4o-transcribe-diarize</p></details></div><span className={'connection-state '+(data.connection.openai?'ready':'')}>{data.connection.openai?'金鑰已設定':'尚未連接'}</span></div><div className="setting-row"><span className="setting-icon sky"><Languages size={23}/></span><div><h3>中英雙向翻譯</h3><p>中文 → English，也能將英文提問翻成繁體中文。</p><details><summary>查看服務資訊</summary><p>OpenAI · {data.connection.translation}<br/>參考課程、前後文及已確認例句。實際效果仍需課堂測試。</p></details></div><span className={'connection-state '+(data.connection.openai?'ready':'')}>{data.connection.openai?'金鑰已設定':'尚未連接'}</span></div><div className="setting-row"><span className="setting-icon sand"><BookOpen size={23}/></span><div><h3>Hermes 長期記憶</h3><p>查詢社課筆記、提出新例句，原意由夥伴確認。</p><div className="button-group"><Button variant="outline" onClick={()=>copyText(location.origin+'/mcp')}><Copy size={15}/>複製連接網址</Button><Button variant="ghost" onClick={()=>window.location.assign('/api/export'+(sessionId?'?session='+sessionId:''))}><Download size={15}/>匯出給 Hermes</Button></div></div><span className="connection-state">尚未連接</span></div><div className="setting-row"><span className="setting-icon sky"><Volume2 size={23}/></span><div><h3>譯文朗讀</h3><p>使用裝置提供的中文與英文聲音。朗讀前請停止收音。</p></div><span className={'connection-state '+(voiceAvailable?'ready':'')}>{voiceAvailable?'裝置支援':'依瀏覽器支援'}</span></div>{!data.connection.openai&&<div className="setup-note"><Info size={20}/><div><h3>OpenAI 尚未完成安全設定</h3><p>目前不能自動辨識或翻譯。可以先建立社課、直接錄製講者樣本、保存文字與確認例句。金鑰請透過安全設定流程處理。</p></div></div>}<p className="fine-note">網站目前是私人工作區。多人使用前，需由網站擁有者設定可存取的夥伴。雙向對話支援同一裝置輪流發言，未加入跨裝置通話。</p></section></TabsContent>
 <footer className="club-footer"><span>禪譯・淡江禪學社</span><span>Change starts with tranquility.</span></footer>
 </main></Tabs>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent className="edit-dialog"><DialogTitle>{dialog==='session'?'為今天的社課開一頁':dialog==='sessionEdit'?'補充今天的社課':dialog==='person'?(editPerson?'編輯夥伴資料':'加入一位夥伴'):dialog==='memory'?(editMemory?'編輯翻譯筆記':'記下這一句'):editSegment?'一起修正這一句':'用文字說一句'}</DialogTitle><DialogDescription>{dialog==='person'?'姓名先填好，聲音可以儲存後直接錄。':dialog==='session'?'主題與講義可以不填，想好名字就能開始。':dialog==='sessionEdit'?'更新名稱、主題或講義；本場紀錄會繼續保留。':dialog==='memory'?'把原意與適用情境說清楚，避免下次用錯。':'選擇發言語言。可以自動翻譯，或填入你確認過的譯文。'}</DialogDescription><form onSubmit={e=>{e.preventDefault();void submit();}} className="edit-form">
 {(dialog==='session'||dialog==='sessionEdit'||dialog==='person')&&<label className="field-label">{dialog==='session'||dialog==='sessionEdit'?'社課名稱':'夥伴姓名'}<Input autoFocus value={name} onChange={e=>setName(e.target.value)} required maxLength={160} placeholder={dialog==='session'||dialog==='sessionEdit'?'例如：覺察與生活':'輸入姓名'}/></label>}
 {(dialog==='session'||dialog==='sessionEdit')&&<details className="optional-fields" open={dialog==='sessionEdit'}><summary>加入課程背景（選填）</summary><label className="field-label">課程主題<Input value={topic} onChange={e=>setTopic(e.target.value)} maxLength={8000}/></label><label className="field-label">講義與背景<Textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={8000} rows={4}/></label></details>}
 {(dialog==='person'||dialog==='segment'||dialog==='memory')&&<div className="form-grid">{dialog!=='person'&&<label className="field-label">{dialog==='memory'?'適用夥伴':'誰說的'}<Picker value={formPerson} onChange={setFormPerson} items={[{value:'none',label:dialog==='memory'?'所有夥伴':'暫不指定'},...data.people.map(p=>({value:p.id,label:p.name}))]} label="選擇人員"/></label>}<label className="field-label">角色<Picker value={formRole} onChange={setFormRole} items={dialog==='memory'?[{value:'通用',label:'通用'},...roleItems]:roleItems} label="選擇角色"/></label></div>}
 {dialog==='person'&&<label className="field-label">常用語或比喻（選填）<Textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={8000} rows={3}/></label>}
 {dialog==='segment'&&!editSegment&&<div className="form-direction"><button type="button" className={formDirection==='zh-en'?'selected':''} onClick={()=>setFormDirection('zh-en')}>中文 → English</button><button type="button" className={formDirection==='en-zh'?'selected':''} onClick={()=>setFormDirection('en-zh')}>English → 中文</button></div>}
 {(dialog==='segment'||dialog==='memory')&&<>{(dialog==='segment'&&formDirection==='en-zh'?['en','zh']:['zh','en']).map(lang=><label key={lang} className="field-label">{lang==='zh'?(dialog==='memory'?'中文':formDirection==='zh-en'?'中文原文':'中文譯文'):(dialog==='memory'?'英文':formDirection==='en-zh'?'English · Original':'英文譯文')}<Textarea lang={lang==='zh'?'zh-Hant':'en'} value={lang==='zh'?zh:en} onChange={e=>lang==='zh'?setZh(e.target.value):setEn(e.target.value)} required={dialog==='memory'||remember||lang===(formDirection==='zh-en'?'zh':'en')} maxLength={8000} rows={3}/></label>)}<label className="field-label">{dialog==='memory'?'真正想說的意思':'原意或修正原因（選填）'}<Textarea value={meaning} onChange={e=>setMeaning(e.target.value)} required={dialog==='memory'||remember} maxLength={8000} rows={2}/></label></>}
 {dialog==='memory'&&<label className="field-label">適用情境<Input value={context} onChange={e=>setContext(e.target.value)} required maxLength={8000} placeholder="例如：靜坐前、引導呼吸"/></label>}
 {dialog==='segment'&&editSegment?.audio_key&&<label className="field-label">重聽這段錄音<audio controls preload="none" src={'/api/recording?id='+editSegment.id}/></label>}
 {dialog==='segment'&&editSegment&&(editSegment.original_zh!==editSegment.zh||editSegment.original_en!==editSegment.en)&&<details className="original-copy"><summary>查看最初的中英內容</summary><p>{editSegment.original_zh||'最初沒有中文'}</p><p lang="en">{editSegment.original_en||'最初沒有英文'}</p></details>}
 {dialog==='segment'&&editSegment&&<label className="remember-control"><Checkbox checked={remember} onCheckedChange={v=>setRemember(v===true)}/><span>中英與原意已確認，也存成翻譯筆記</span></label>}
 <div className="dialog-buttons"><Button type="button" variant="ghost" disabled={busy} onClick={()=>setDialog(null)}>稍後再說</Button>{dialog==='segment'&&!editSegment&&<Button type="button" variant="outline" disabled={busy||!data.connection.openai||!(formDirection==='zh-en'?zh:en).trim()} onClick={()=>submit(true)}><Languages size={16}/>翻譯並保存</Button>}<Button type="submit" disabled={busy}>{busy?'保存中…':dialog==='session'?'建立社課':'保存'}</Button></div>
 </form></DialogContent></Dialog>
 </div>;
}
