// PostgreSQL equivalent of db/schema.ts; IDs and ISO dates preserve the existing API.
import {pgTable,text,integer,doublePrecision,index,uniqueIndex,primaryKey} from 'drizzle-orm/pg-core';
export const people=pgTable('people',{id:text('id').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),notes:text('notes').notNull().default(''),referenceKey:text('reference_key'),referenceType:text('reference_type'),createdAt:text('created_at').notNull()});
export const sessions=pgTable('sessions',{id:text('id').primaryKey(),title:text('title').notNull(),topic:text('topic').notNull().default(''),notes:text('notes').notNull().default(''),roles:text('roles').notNull().default('{}'),speakerIds:text('speaker_ids').notNull().default('[]'),status:text('status').notNull().default('ready'),createdAt:text('created_at').notNull()});
export const segments=pgTable('segments',{id:text('id').primaryKey(),sessionId:text('session_id').notNull().references(()=>sessions.id),personId:text('person_id').references(()=>people.id),label:text('label').notNull(),role:text('role').notNull(),direction:text('direction').notNull().default('zh-en'),zh:text('zh').notNull(),en:text('en').notNull().default(''),originalZh:text('original_zh').notNull().default(''),originalEn:text('original_en').notNull().default(''),note:text('note').notNull().default(''),audioKey:text('audio_key'),offset:doublePrecision('offset').notNull().default(0),source:text('source').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_segments_session_created').on(t.sessionId,t.createdAt)]);
export const memories=pgTable('memories',{id:text('id').primaryKey(),personId:text('person_id').references(()=>people.id),role:text('role').notNull().default('通用'),zh:text('zh').notNull(),en:text('en').notNull(),meaning:text('meaning').notNull().default(''),context:text('context').notNull().default(''),status:text('status').notNull().default('candidate'),sourceId:text('source_id').references(()=>segments.id),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_memories_status_person').on(t.status,t.personId),uniqueIndex('idx_memories_source').on(t.sourceId)]);
export const memoryRevisions=pgTable('memory_revisions',{id:text('id').primaryKey(),memoryId:text('memory_id').notNull().references(()=>memories.id),payload:text('payload').notNull(),createdAt:text('created_at').notNull()});
export const segmentRevisions=pgTable('segment_revisions',{id:text('id').primaryKey(),segmentId:text('segment_id').notNull().references(()=>segments.id),payload:text('payload').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_segment_revisions_segment').on(t.segmentId)]);

export const dictionarySources=pgTable('dictionary_sources',{id:text('id').primaryKey(),title:text('title').notNull(),license:text('license').notNull(),licenseUrl:text('license_url').notNull().default(''),sourceUrl:text('source_url').notNull().default(''),version:text('version').notNull().default(''),sha256:text('sha256').notNull().default(''),entryCount:integer('entry_count').notNull().default(0),public:integer('public').notNull().default(0),updatedAt:text('updated_at').notNull()});
export const dictionaryEntries=pgTable('dictionary_entries',{id:text('id').primaryKey(),sourceId:text('source_id').notNull().references(()=>dictionarySources.id),snapshot:text('snapshot').notNull(),word:text('word').notNull(),alternative:text('alternative').notNull().default(''),pronunciation:text('pronunciation').notNull().default(''),zh:text('zh').notNull().default(''),en:text('en').notNull().default('')},t=>[index('idx_dictionary_snapshot').on(t.sourceId,t.snapshot)]);
export const dictionaryKeys=pgTable('dictionary_keys',{entryId:text('entry_id').notNull().references(()=>dictionaryEntries.id),key:text('key').notNull()},t=>[primaryKey({columns:[t.entryId,t.key]}),index('idx_dictionary_key').on(t.key)]);
